name: haskell-debug-adapter
version: '0.0.1.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Development
author: Author name here
maintainer: example@example.com
copyright: 2017 Author Here
license: BSD3
homepage: http://github.com/githubuser/haskell-debug-adapter#readme

extra-source-files:
- README.md
- Changelog.md

ghc-options:
- -Wall
- -Werror
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-orphans
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - Paths_haskell_debug_adapter
  - Haskell.Debug.Adapter.Constant
  - Haskell.Debug.Adapter.Control
  - Haskell.Debug.Adapter.Logger
  - Haskell.Debug.Adapter.Type
  - Haskell.Debug.Adapter.Utility
  - Haskell.Debug.Adapter.Application
  - Haskell.Debug.Adapter.Request
  - Haskell.Debug.Adapter.Response
  - Haskell.Debug.Adapter.Thread
  - Haskell.Debug.Adapter.TH.Utility
  dependencies:
  - base >=4.7 && <5
  - mtl
  - hslogger
  - text
  - bytestring
  - MissingH
  - conduit
  - conduit-extra
  - resourcet
  - lens
  - safe-exceptions
  - aeson
  - data-default
  - containers
  - parsec
  - async
  - directory
  - filepath
  - process
  - Cabal
  - clock
  - haskell-dap
  
executables:
  haskell-debug-adapter:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - haskell-debug-adapter
    - hslogger
    - MissingH
    - safe
    - lens
    - safe-exceptions
    - aeson
    - yaml
    - bytestring
    - text
    - cmdargs

tests:
  haskell-debug-adapter-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - haskell-debug-adapter
    - base
    - hspec
    - bytestring
    - data-default
    - process
    - async
    - aeson
    - lens
    - safe-exceptions
    - hslogger
